In [ ]:
import torch

def weighted_pool(arr: torch.Tensor | SupportsIndex, row: int, col: int, kernel: torch.Tensor) -> list:   
    weighted_sum = 0.0
    kernel_weights_used = 0.0
    
    _kernel_lrow = kernel.shape[0] // 2 # radius along rows (horizontal), also the center row of the kernel
    _kernel_lcol = kernel.shape[1] // 2 # radius along cols (vertical), also the center col of the kernel
    
    arr_interior = arr[_kernel_lrow:-_kernel_lrow, _kernel_lcol:-_kernel_lcol]
    
    # optimize to only weighted pool the edges, not going through all the interior
    for mov_row in range(-_kernel_lrow, _kernel_lrow + 1):
        for mov_col in range(-_kernel_lcol, _kernel_lcol + 1):
            if _index_out_of_bounds(arr, row + mov_row, col + mov_col):
                continue
            
            weight = kernel[mov_row + _kernel_lrow][mov_col + _kernel_lcol]
            _dot = weight * arr[row + mov_row][col + mov_col]
            weighted_sum += _dot
            kernel_weights_used += weight
            
    return weighted_sum / kernel_weights_used

In [6]:
import torch

tensor1 = torch.Tensor([[[
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
]]])

kernel = torch.Tensor([[[
    [0, 0, 0],
    [0, 4, 0],
    [0, 0, 0]
]]])

convolved = torch.nn.functional.conv2d(
    input=tensor1,
    weight=kernel
)



print(convolved)

tensor([[[[28., 32., 36.],
          [48., 52., 56.],
          [68., 72., 76.]]]])


In [17]:
def get_edge_indices(length, width, border_width):
    edge_indices = []
    for i in range(length):
        if i < border_width or i >= length - border_width:
            edge_indices.extend([(i, j) for j in range(width)])
        else:
            for j in range(border_width):
                edge_indices.extend([(i, j), (i, width - 1 - j)])
    return edge_indices

testarr = [
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
]

for coord in get_edge_indices(5, 5, 2):
    testarr[coord[0]][coord[1]] = 0
    
for row in testarr:
    print(row)


[0, 0, 0, 0, 0]
[0, 0, 0, 0, 0]
[0, 0, 13, 0, 0]
[0, 0, 0, 0, 0]
[0, 0, 0, 0, 0]


In [2]:
import torch

tensor1 = torch.Tensor([
    [0.5, 0.5, 3],
    [4, 5, 6],
    [7, 8, 9]
]).long()

coord = (0, 1)
print(tensor1[*coord])

tensor(0)


In [3]:
import torch

tens1 = torch.Tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

tens1 = tens1/10

print(tens1)

tensor([[0.1000, 0.2000, 0.3000],
        [0.4000, 0.5000, 0.6000],
        [0.7000, 0.8000, 0.9000]])


In [4]:
import torch

tensor1 = torch.Tensor([[[
    [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
    [0.0000, 0.0000, 0.2000, 0.2000, 0.2000, 0.0000, 0.0000],
    [0.0000, 0.2000, 0.6000, 0.8000, 0.6000, 0.2000, 0.0000],
    [0.0000, 0.2000, 0.8000, 1.0000, 0.8000, 0.2000, 0.0000],
    [0.0000, 0.2000, 0.6000, 0.8000, 0.6000, 0.2000, 0.0000],
    [0.0000, 0.0000, 0.2000, 0.2000, 0.2000, 0.0000, 0.0000],
    [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000]
]]])

conved = torch.nn.functional.conv2d(
    tensor1, 
    torch.Tensor([[[
        [0, 1, 0],
        [1, 1, 1],
        [0, 1, 0]
    ]]])
)

print(conved / 5)

tensor([[[[0.0800, 0.2000, 0.2800, 0.2000, 0.0800],
          [0.2000, 0.5200, 0.6400, 0.5200, 0.2000],
          [0.2800, 0.6400, 0.8400, 0.6400, 0.2800],
          [0.2000, 0.5200, 0.6400, 0.5200, 0.2000],
          [0.0800, 0.2000, 0.2800, 0.2000, 0.0800]]]])
